# Generated by Django 4.2.7 on 2023-12-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timezone',
            field=models.CharField(default='UTC', max_length=32),
        ),
    ]
