# Generated by Django 4.2.7 on 2023-12-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['request_time', 'selected_date'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='course_choose',
            field=models.CharField(default='Консультация', max_length=200, verbose_name='Тема обращения'),
        ),
    ]
