# Generated by Django 3.2.20 on 2023-12-15 10:14

import app_loging.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loging', '0002_auto_20231215_1013'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app_loging.models.UserManager()),
            ],
        ),
    ]
