# Generated by Django 3.2.20 on 2023-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loging', '0004_alter_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(default='Пусто', max_length=500),
        ),
    ]
