# Generated by Django 3.2.20 on 2023-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='git',
            field=models.URLField(max_length=1000),
        ),
    ]
