# Generated by Django 3.2.20 on 2023-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_projects_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='git',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
