# Generated by Django 3.2.20 on 2023-12-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20231215_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-dt',), 'verbose_name': 'Заказов', 'verbose_name_plural': 'Список заказов'},
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_info',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='shop.product', verbose_name='Информация о продукте'),
            preserve_default=False,
        ),
    ]
