# Generated by Django 3.2.20 on 2023-12-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
